server:
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.yvenxvgkgcfbpvwerjvr
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10
    connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


tour-api:
  service-key: VSRjuqr0bQ8H3qPSxevdKSdZK/6gYpdKUlS2cBeQvfo66fPUaEzbG+eoCoPelUKDsa2nZBQtHM72Hx21FlVn2A==
  base-url: https://apis.data.go.kr/B551011/KorService2
